pr:
  branches:
    include:
      - main
  paths:
    include:
      - .azure_pipelines_attestation_container.yml
      - .attestation_container_canary

trigger:
  - main

jobs:
  - template: .azure-pipelines-templates/configure.yml

  - template: .azure-pipelines-templates/deploy_aci.yml
    parameters:
      used_by:
        - test_snp

  - template: .azure-pipelines-templates/test_on_remote.yml
    parameters:
      job_name: test_snp
      display_name: "Test SNP"
      depends_on: deploy_aci
      run_on: $[ dependencies.deploy_aci.outputs['deploy_aci.ipAddresses'] ]
      host_private_key: $[ dependencies.deploy_aci.outputs['generate_ssh_key.hostPrivKey'] ]
